version: '3'

services:
  database:
    image: mariadb:10.7.3
    restart: unless-stopped
    container_name: oauth-prod-db
    environment:
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: devscast
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'no'
    volumes:
      - database-data:/var/lib/mysql:rw
      - ./var:/var/www/var
    labels:
      com.symfony.server.service-prefix: 'DATABASE'

  web:
    image: nginx:alpine
    container_name: oauth-prod-web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www:delegated
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    user: '${USER_ID}:${GROUP_ID}'
    image: grafikart/php:php8.2-2
    container_name: oauth-prod-php
    restart: unless-stopped
    volumes:
      - .:/var/www:delegated
    depends_on:
      - database

  adminer:
    image: adminer:4.8.1
    restart: unless-stopped
    container_name: oauth-prod-adminer
    depends_on:
      - database
    environment:
      APP_ENV: dev
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: database
    ports:
      - "8082:8080"

volumes:
  database-data:
    driver:
      local
